//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalary
    {
        public int Id { get; set; }
        public Nullable<int> Hours { get; set; }
        public string HourlyRate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> WeekId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual WeekNumber WeekNumber { get; set; }
    }
}
