//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryRecord
    {
        public int Id { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public string Date { get; set; }
        public Nullable<int> WeekId { get; set; }
        public string VenderName { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual WeekNumber WeekNumber { get; set; }
    }
}
