//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalRevenue
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Less { get; set; }
        public Nullable<double> Add { get; set; }
        public Nullable<double> PreviousBalance { get; set; }
        public Nullable<double> CurrentBalance { get; set; }
        public Nullable<int> WeekId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual WeekNumber WeekNumber { get; set; }
    }
}
